name: Deploy WASM Pages

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to deploy"
        required: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitHub API to delete Pages site
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ROFFICE_RELEASE }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pages

      - name: Fetch release by tag
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const tag = '${{ github.event.inputs.tag }}';
            const res = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tag
            });

            const assets = res.data.assets;
            const wasmAsset = assets.find(asset =>
              asset.name.toLowerCase().includes("wasm") &&
              asset.name.toLowerCase().endsWith(".zip")
            );

            if (!wasmAsset) {
              core.setFailed("No wasm zip asset found in this release.");
              return;
            }

            core.setOutput("asset_url", wasmAsset.url);
            core.setOutput("asset_name", wasmAsset.name);

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download wasm zip
        run: |
          echo "Downloading: ${{ steps.get_release.outputs.asset_name }}"
          curl -L -H "Accept: application/octet-stream" \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               "${{ steps.get_release.outputs.asset_url }}" \
               -o "${{ steps.get_release.outputs.asset_name }}"

      - name: Unzip
        run: unzip "${{ steps.get_release.outputs.asset_name }}" -d ./site

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: wasm-pages
          path: ./site/wasm32-unknown-emscripten

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: wasm-pages
